name: build-workflow

on:
  push:

jobs:
  build-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - working-directory: davidecalarco
        run: npm install --no-audit --no-fund
      - working-directory: davidecalarco
        run: npm run build
  
  test-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - working-directory: davidecalarco
        run: npm install --no-audit --no-fund
      - working-directory: davidecalarco
        run: npm run test