name: build-workflow

on:
  push:

jobs:
  build-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - working-directory: davidecalarco
        run: |
          npm install --no-audit --no-fund
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build output
          path: davidecalarco/dist
  
  test-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - working-directory: davidecalarco
        run: |
          npm install --no-audit --no-fund
          npm run test