name: build-workflow
on:
  push:

jobs:
  build-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: davidecalarco/npm-shrinkwrap.json
      - working-directory: davidecalarco
        name: build
        run: |
          npm ci --cache npm --prefer-offline --no-audit --no-fund
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build output
          path: davidecalarco/dist
  
  test-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: davidecalarco/npm-shrinkwrap.json
      - working-directory: davidecalarco
        name: test
        run: |
          npm ci --cache npm --prefer-offline --no-audit --no-fund
          npm run test